import "./globals.css";
import { Inter } from "next/font/google";
import AOSInitialize from "@/utils/aos";
import ScrollToTop from "@/utils/scrollToTop";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "شرکت فنجان داغ خوارزمی - SET Coffee | فروشگاه اینترنتی قهوه ست",
  description: "SET Coffee App Generated by create-next-app@13",
  icons: {
    icon: "./icon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <AOSInitialize />
      <body className={inter.className}>
        {children}
        <ScrollToTop />
      </body>
    </html>
  );
}
